services:
  # Ollama hosting servie
  ollama:
    image: ollama/ollama:latest
    build:
      context: . # set current directory
      dockerfile: Dockerfile_ollama
      # platforms:
      #   - linux/arm64
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # Persist Ollama model data to a named volume
    # ** existing **
    command: ["serve"] # run 'ollama serve' as the main command for this container
    # ** attempt to serve and pull **
    # entrypoint: ["ollama", "serve"]
    
    healthcheck: # healthcheck for ollama-init to see if its healthy
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - joya_network # custom network for inter-service communication

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama_puller
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: [ "sh", "-c"]
    command:
      ["ollama pull gemma3:1b && ollama pull nomic-embed-text"]
    depends_on:
      ollama:
        condition: service_healthy # Wait for Ollama to be ready to accept commands
    networks:
      - joya_network

  # Service for FastAPI application
  joya_api:
    image: johnryanmcnally/joya_api:latest
    build:
      context: .
      dockerfile: Dockerfile_joya_api
      # platforms:
      #   - linux/arm64
      #   - linux/X86_64
    container_name: joya_api
    ports:
      - "8000:8000"
    environment:
      CHROMA_DB_PATH: "./chroma_langchain_db" # Set the CHROMA_DB_PATH environment variable for the FastAPI app
    depends_on:
      ollama-pull:
        condition: service_completed_successfully # Start API only after models are pulled
      ollama:
        condition: service_healthy
    networks:
      - joya_network

# Define named volumes for persistent data
volumes:
  ollama_data:

# Define a custom network for the services to communicate with each other
networks:
  joya_network:
    driver: bridge
