# base image
FROM python:3.13-slim-bookworm

# set working directory
WORKDIR /app

# install curl -- I don't think this is necessary anymore in this file
# RUN apt-get update && apt-get install -y curl

# Install system dependencies needed for sqlite
RUN apt-get update && apt-get install -y --no-install-recommends \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

# copy files
COPY joya_api/api_requirements.txt .

# install packages
RUN pip install --no-cache-dir -r api_requirements.txt

# Copy the joya_api directory into the container
COPY joya_api/ .

# Expose the port that FastAPI will run on
EXPOSE 8000

# run the FastAPI using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
